// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"greet/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: pingHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ping123",
				Handler: ping123Handler(serverCtx),
			},
		},

	)
}
