// Code generated by goctl. DO NOT EDIT.
// Source: abc.proto

package server

import (
	"context"

	"greet/abc/abc"
	"greet/abc/internal/logic"
	"greet/abc/internal/svc"
)

type AbcServer struct {
	svcCtx *svc.ServiceContext
	abc.UnimplementedAbcServer
}

func NewAbcServer(svcCtx *svc.ServiceContext) *AbcServer {
	return &AbcServer{
		svcCtx: svcCtx,
	}
}

func (s *AbcServer) Ping(ctx context.Context, in *abc.Request) (*abc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
